spring :
  jpa :
    show-sql : true
    format-sql : true
    use_sql_comments : true
    new_generator_mappings : false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB53Dialect
  datasource:
      url: jdbc:mysql://54.180.220.116:3306/SHOPPING_MALL
      username: root
      password: mariadb
      driver-class-name: org.mariadb.jdbc.Driver

